#!/usr/bin/env bash#
# opens iTerm2
alt - return : "${HOME}"/.config/yabai/scripts/open_iterm2.sh

# Show system statistics


# Navigation 在Space内根据方向键移动焦点
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east


# toggle window split type 横向平铺和纵向平铺切换
alt - e : yabai -m window --toggle split

# Rotate windows clockwise and anticlockwise 顺时90/270针旋转Space内的窗格
alt - r         : yabai -m space --rotate 90
shift + alt - r : yabai -m space --rotate 270

# Float / Unfloat window (更换 layout 方式) 开关平铺布局模式
shift + alt - space : yabai -m window --toggle float

# Moving windows 在Space内根据方向键来移动窗格
shift + alt - h : yabai -m window --warp west
shift + alt - j : yabai -m window --warp south
shift + alt - k : yabai -m window --warp north
shift + alt - l : yabai -m window --warp east

# Float and center window 把当前的焦点窗口居中 重点突出该窗口
shift + alt - c : yabai -m window --toggle float;\
                  yabai -m window --grid 4:4:1:1:2:2

# Rotate on X and Y Axis 水平轴｜竖直轴方向翻转Space内的窗格
shift + alt - x : yabai -m space --mirror x-axis
shift + alt - y : yabai -m space --mirror y-axis

# Make window native fullscreen 缩放全凭 真全屏
alt - f         : yabai -m window --toggle zoom-fullscreen
shift + alt - f : yabai -m window --toggle native-fullscreen

# increase window size 竖直方向才能用 top  水平方向才能用 left
shift + alt - d : yabai -m window --resize left:-20:0
shift + alt - w : yabai -m window --resize top:0:-20
# decrease window size
shift + alt - a : yabai -m window --resize left:20:0
shift + alt - s : yabai -m window --resize top:0:20








# send window to space 移动窗格到指定的Space
ctrl + shift - 1 : yabai -m window --space 1
ctrl + shift - 2 : yabai -m window --space 2
ctrl + shift - 3 : yabai -m window --space 3
ctrl + shift - 4 : yabai -m window --space 4
ctrl + shift - 5 : yabai -m window --space 5
ctrl + shift - 6 : yabai -m window --space 6
ctrl + shift - 7 : yabai -m window --space 7
ctrl + shift - 8 : yabai -m window --space 8
ctrl + shift - 9 : yabai -m window --space 9
ctrl + shift - 0 : yabai -m window --space 10










# Equalize size of windows 让窗格平分Space的空间
lctrl + alt - 0 : yabai -m space --balance

# Enable / Disable gaps in current workspace 开关窗格带间隔模式
lctrl + alt - g : yabai -m space --toggle padding; yabai -m space --toggle gap

alt + ctrl - f : yabai -m space --layout float && \
                 yabai -m config window_border off
alt + ctrl - b : yabai -m space --layout bsp && \
                 yabai -m config window_border on











# Set insertion point for focused container
shift + lctrl + alt - h : yabai -m window --insert west
shift + lctrl + alt - j : yabai -m window --insert south
shift + lctrl + alt - k : yabai -m window --insert north
shift + lctrl + alt - l : yabai -m window --insert east









# Resize windows 调整Space内的窗格大小
 ##shift+ cmd - h : \
     ##yabai -m window --resize left:-20:0 ; \
     ##yabai -m window --resize right:-20:0
shift + cmd - h : yabai -m window --resize left:-20:0

shift + cmd - j : \
    yabai -m window --resize bottom:0:20 ; \
    yabai -m window --resize top:0:20

shift + cmd - k : \
    yabai -m window --resize top:0:-20 ; \
    yabai -m window --resize bottom:0:-20

shift + cmd - l : \
    yabai -m window --resize right:20:0 ; \
    yabai -m window --resize left:20:0
# Move focus container to workspace 移动当前的焦点窗格到制定的Space
shift + cmd - m : yabai -m window --space last && yabai -m space --focus last
shift + cmd - b : yabai -m window --space prev && yabai -m space --focus prev
shift + cmd - n : yabai -m window --space next && yabai -m space --focus next
shift + cmd - 1 : yabai -m window --space 1 && yabai -m space --focus 1
shift + cmd - 2 : yabai -m window --space 2 && yabai -m space --focus 2
shift + cmd - 3 : yabai -m window --space 3 && yabai -m space --focus 3
shift + cmd - 4 : yabai -m window --space 4 && yabai -m space --focus 4
shift + cmd - 5 : yabai -m window --space 5 && yabai -m space --focus 5
shift + cmd - 6 : yabai -m window --space 6 && yabai -m space --focus 6









# Restart Yabai
shift + cmd + alt - r :
    /usr/bin/env osascript <<< \
        "display notification \"Restarting Yabai\" with title \"Yabai\""; \
    launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"









###################下面需要禁用系统完整性保护####################
###################下面需要禁用系统完整性保护####################
###################下面需要禁用系统完整性保护####################

# fast focus desktop (切换空间焦点)
# cmd + alt - x : yabai -m space --focus recent
# cmd + alt - z : yabai -m space --focus prev
# cmd + alt - c : yabai -m space --focus next
alt - 1 : yabai -m space --focus 1
alt - 2 : yabai -m space --focus 2
alt - 3 : yabai -m space --focus 3
alt - 4 : yabai -m space --focus 4
alt - 5 : yabai -m space --focus 5
alt - 6 : yabai -m space --focus 6
alt - 7 : yabai -m space --focus 7
alt - 8 : yabai -m space --focus 8
alt - 9 : yabai -m space --focus 9
alt - 0 : yabai -m space --focus 10

# create new space
ctrl - n : yabai -m space --create

